import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Bounce, ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable:"--font-poppins",
  weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} zantialiased`}
      >
        <ToastContainer 
          position="bottom-right"
          autoClose={1000}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          hideProgressBar
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Bounce}
        />

        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
